import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const workSans = localFont({
  src: [
    {
      path: "./assets/fonts/WorkSans-VariableFont_wght.ttf",
      weight: '100 900',
      style: 'normal',
    },
    {
      path: './assets/fonts/WorkSans-Italic-VariableFont_wght.ttf',
      weight: '100 900',
      style: 'italic',
    },
    
  ],
  variable: '--font-work-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "FAQ ACCORDIAN STYLE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
